fix native

diff --git a/.pre-commit-hooks.yaml b/.pre-commit-hooks.yaml
--- a/.pre-commit-hooks.yaml
+++ b/.pre-commit-hooks.yaml
@@ -21,7 +21,12 @@
 
 -   id: gbp-remote-has-tag
     name: remote repo has tag
-    entry: bash -c 'echo upstream/$(head -n 1 debian/changelog | grep -oP "\(\K([0-9]+:)?\K[0-9]+(\.[0-9]+)*")$ | grep -f - <(git ls-remote --tags origin) || (echo "Missing upstream version tag!" && exit 1)'
+    entry: >
+        bash -c '
+        if grep -q "^3.0 (quilt)$" debian/source/format; then
+            echo upstream/$(head -n 1 debian/changelog | grep -oP "\(\K([0-9]+:)?\K[0-9]+(\.[0-9]+)*")$ | grep -f - <(git ls-remote --tags origin) || (echo "Missing upstream version tag!" && exit 1);
+        fi;
+        exit 0'
     language: system
     always_run: true
 
@@ -78,7 +83,8 @@
           echo "$version" | grep -qP "\-\d+" || (echo "Quilt format requires version with -[0-9] suffix, found: $version" && exit 1);
       else
           echo "$version" | grep -qP "\-\d+" && (echo "Native format requires version without -[0-9] suffix, found: $version" && exit 1);
-      fi'
+      fi;
+      exit 0'
     language: system
     always_run: true
     types: [file]
